### ISSUE TITLE
OrderLine - 20200204

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#55]
- [ ] Added a bell icon while an order rings:
![image](https://user-images.githubusercontent.com/5095197/73765923-9254d400-4775-11ea-99dc-a4fce83633e3.png)

- [ ] Status button design change: https://github.com/HubRise/orderline/issues/80

- [ ] Swapped two rows of dropdowns in Settings / Notifications: https://github.com/HubRise/orderline/issues/81

- [ ] Status button design improvments + confirmed time is no longer set until explicitly selected by the user: https://github.com/HubRise/orderline/issues/82

**Comment by antmonnier** [comment]
@janainawittner You can close this issue when the changes described above are included in the documentation.
